

DESC = {
    'BluePotion': 'A potion that increases\nyour health\nClick to use',
    'OrangePotion': 'A potion that increases\nyour damage\nClick to use',
    'HedgehogCarcass': 'The carcass of a dead\nhedgehog',
    'SquirrelCarcass': 'The carcass of a dead\nsquirrel',
    'BlueBerries': 'Some blue berries\nCan be used to make potions',
    'OrangeBerries': 'Some orange berries\nCan be used to make potions',
    'Wood': 'A basic crafting material',
    'StonesSmall': 'A basic crafting material',
    'AxeBasic': 'A basic axe that can be used\nto collect wood\nClick to equip\nAttack trees and ships to use',
    'PickBasic': 'A basic pickaxe that can be\nused to collect minerals\nClick to equip\nAttack rocks to use',
    'SwordBasic': 'A basic sword that can\nincrease your attack strength\nClick to equip',
    'Plank': 'A more advanced building\nmaterial',
    'BasicCraftingTable': 'A crafting table that can be used\nto craft more advanced materials\nClick to place',
    'BlueBrick': 'A more advanced crafting\nmaterial',
    'BluePowder': 'A powder used in advanced\ncrafting',
    'Brick': 'A more advanced crafting\nmaterial',
    'OrangeBrick': 'A more advanced crafting\nmaterial',
    'OrangePowder': 'A powder used in advanced\ncrafting',
    'RockBasic': 'A basic crafting\nmaterial',
    'Rock': 'A basic crafting\nmaterial',
    'RockBlue': 'A basic crafting\nmaterial',
    'RockOrange': 'A basic crafting\nmaterial',
    'SmallStonesBlue': 'A basic crafting\nmaterial',
    'SmallStonesOrange': 'A basic crafting\nmaterial',
    'Firestarter': 'Flint and steel used to start\nfires',
    'Campfire': 'A campfire to light up the\nnight and cook food\nClick to place',
    'MeatCooked': 'A small chunk of\ncooked meat\nClick to consume'
}
